### ISSUE TITLE
the ui page can't be visited ?

### ISSUE THREAD

**Issue by shyding** [openwms/org.openwms.tms.routing#57]
after mvn package  and  java -jar target/openwms-tms-routing-exec.jar
the ui page of REACT_APP_PUBLIC_URL=http://localhost:8130/ui still can't be visited but found 404 .

**Comment by openwms** [comment]
There is no UI specific for the Routing service anymore.The concept has changed from a microfrontend (in 2017) to a modular and customer centric UI in 2020 that fulfills the demanded uses cases - nothing more nothing less. 

The description has already been adopted.
